import * as i from "../instructions"
import {compileCell} from "../instructions"
import {
    address,
    Address,
    beginCell,
    BitString,
    Cell,
    Contract,
    contractAddress,
    ContractProvider,
    Sender,
    StateInit,
    toNano,
    TupleBuilder,
    TupleReader,
} from "@ton/core"
import {Blockchain, SandboxContract, TreasuryContract} from "@ton/sandbox"
import {Hash} from "../instructions/asm1"
import {debug} from "../instructions/helpers"

describe("whole-contract-tests", () => {
    it(`Test simple counter`, async () => {
        const instructions = [
            i.SETCP(0),
            i.PUSHDICTCONST(new Map([
                [0, [
                    // i.POP(0),
                    i.SWAP(),
                    i.CTOS(),
                    i.PUSHINT(2),
                    i.SDSKIPFIRST(),
                    i.LDI(1),
                    i.LDI(1),
                    i.LDMSGADDR(),
                    i.PUSH(1),
                    i.XCHG_1([3, 4]),
                    i.XCHG2(6 , 6),
                    i.TUPLE(4),
                    i.SETGLOB(1),
                    i.XCHG_0(2),
                    i.SETGLOB(2),
                    i.PUSHCTR(4),
                    i.CTOS(),
                    i.LDI(1),
                    i.SWAP(),
                    i.PUSHCONT_SHORT([
                        i.LDU(32),
                        i.LDU(32),
                        i.ROTREV(),
                        i.BLKDROP2([1 , 2]),
                    ]),
                    i.PUSHCONT_SHORT([
                        i.PUSHINT_16(257),
                        i.LDIX(),
                        i.SWAP(),
                        i.SWAP(),
                        i.ENDS(),
                        i.PUSHINT(0),
                    ]),
                    i.IFELSE(),
                    i.XCHG_0(3),
                    i.PUSHCONT_SHORT([
                        i.BLKDROP(3),
                    ]),
                    i.IFJMP(),
                    i.PUSHINT(0),
                    i.PUSH(2),
                    i.SBITS(),
                    i.PUSH(0),
                    i.GTINT(31),
                    i.PUSHCONT_SHORT([
                        i.POP(1),
                        i.XCHG_0(2),
                        i.LDU(32),
                        i.XCHG_0(3),
                    ]),
                    i.IF(),
                    i.PUSH(1),
                    i.PUSHINT_LONG(2335447074n),
                    i.EQUAL(),
                    i.PUSHCONT([
                        i.DROP2(),
                        i.SWAP(),
                        i.LDU(64),
                        i.LDU(32),
                        i.ROTREV(),
                        i.BLKDROP2([2 , 1]),
                        i.XCHG_1([1, 2]),
                        i.ADD(),
                        i.NEWC(),
                        i.PUSHINT(-1),
                        i.SWAP(),
                        i.STI(1),
                        i.ROTREV(),
                        i.XCHG_0(2),
                        i.STU(32),
                        i.STU(32),
                        i.ENDC(),
                        i.POPCTR(4),
                    ]),
                    i.IFJMP(),
                    i.POP(3),
                    i.EQINT(0),
                    i.XCHG_0(2),
                    i.LESSINT(33),
                    i.XCHG_1([1, 2]),
                    i.AND(),
                    i.IFJMPREF([
                        i.SWAP(),
                        i.NEWC(),
                        i.PUSHINT(-1),
                        i.SWAP(),
                        i.STI(1),
                        i.ROTREV(),
                        i.XCHG_0(2),
                        i.STU(32),
                        i.STU(32),
                        i.ENDC(),
                        i.POPCTR(4),
                    ]),
                    i.DROP2(),
                    i.THROW(130),
                ]],
                [65536, [
                    i.PUSHCTR(4),
                    i.CTOS(),
                    i.LDI(1),
                    i.SWAP(),
                    i.PUSHCONT_SHORT([
                        i.LDU(32),
                        i.LDU(32),
                        i.ROTREV(),
                        i.BLKDROP2([1 , 2]),
                    ]),
                    i.PUSHCONT_SHORT([
                        i.PUSHINT_16(257),
                        i.LDIX(),
                        i.SWAP(),
                        i.SWAP(),
                        i.ENDS(),
                        i.PUSHINT(0),
                    ]),
                    i.IFELSE(),
                    i.CALLREF([
                        i.PUSH(0),
                    ]),
                    i.BLKDROP2([2 , 1]),
                ]],
                [105872, [
                    i.PUSHCTR(4),
                    i.CTOS(),
                    i.LDI(1),
                    i.SWAP(),
                    i.PUSHCONT_SHORT([
                        i.LDU(32),
                        i.LDU(32),
                        i.ROTREV(),
                        i.BLKDROP2([1 , 2]),
                    ]),
                    i.PUSHCONT_SHORT([
                        i.PUSHINT_16(257),
                        i.LDIX(),
                        i.SWAP(),
                        i.SWAP(),
                        i.ENDS(),
                        i.PUSHINT(0),
                    ]),
                    i.IFELSE(),
                    i.CALLREF([
                        i.PUSH(1),
                    ]),
                    i.BLKDROP2([2 , 1]),
                ]],
            ])),
            i.DICTIGETJMPZ(),
            i.THROWARG(11),
        ]

        const blockchain: Blockchain = await Blockchain.create()
        blockchain.verbosity.vmLogs = "vm_logs_verbose"
        const treasure: SandboxContract<TreasuryContract> = await blockchain.treasury("treasure")

        const init: StateInit = {
            code: compileCell(instructions),
            data: beginCell().storeUint(1, 1).storeInt(123, 32).storeInt(456, 32).endCell(),
        }

        const address = contractAddress(0, init)
        const contract = new TestContract(address, init)

        const openContract = blockchain.openContract(contract)

        // Deploy
        await openContract.send( treasure.getSender(), {
            value: toNano("10"),
        }, new Cell())

        // send an Add message
        await openContract.send( treasure.getSender(), {
            value: toNano("10"),
        }, beginCell()
            .storeUint(2335447074, 32)
            .storeUint(1, 64) // queryId
            .storeUint(100, 32) // amount
            .endCell()
        )

        const data = await openContract.getAny(65536)
        const num = data.readBigNumber()
        expect(Number(num)).toEqual(556)
    })

    it(`Test Jetton Wallet`, async () => {
        // console.log(i.hex("6_"))
        // return

        const instructions = [
            i.SETCP(0),
            i.PUSH(0),
            i.PUSHCONT([
                i.POP(0),
                i.PSEUDO_PUSHREF([
                    i.SWAP(),
                    i.CTOS(),
                    i.PUSHINT(2),
                    i.SDSKIPFIRST(),
                    i.LDI(1),
                    i.LDI(1),
                    i.LDMSGADDR(),
                    i.PUSH(1),
                    i.XCHG_1([3, 4]),
                    i.XCHG2(6 , 6),
                    i.TUPLE(4),
                    i.SETGLOB(1),
                    i.XCHG_0(2),
                    i.SETGLOB(2),
                    i.PUSHCTR(4),
                    i.CTOS(),
                    i.LDGRAMS(),
                    i.LDMSGADDR(),
                    i.LDMSGADDR(),
                    i.BLKSWAP(3 , 1),
                    i.BLKDROP2([1 , 3]),
                    i.XCHG_0(4),
                    i.IFJMPREF([
                        i.XCHG_0(2),
                        i.PUSHINT_8(32),
                        i.SDSKIPFIRST(),
                        i.PUSHINT(0),
                        i.PUSH(1),
                        i.SBITS(),
                        i.GTINT(31),
                        i.PUSHCONT_SHORT([
                            i.POP(0),
                            i.LDU(32),
                            i.SWAP(),
                        ]),
                        i.IF(),
                        i.PUSH(0),
                        i.PUSHINT_LONG(395134233n),
                        i.EQUAL(),
                        i.PUSHCONT([
                            i.POP(0),
                            i.LDU(64),
                            i.LDGRAMS(),
                            i.ROTREV(),
                            i.BLKDROP2([2 , 1]),
                            i.ADD(),
                            i.XCHG_0(2),
                            i.NEWC(),
                            i.BLKSWAP(3 , 1),
                            i.SWAP2(),
                            i.STGRAMS(),
                            i.ROT(),
                            i.STSLICER(),
                            i.SWAP(),
                            i.STSLICER(),
                            i.ENDC(),
                            i.POPCTR(4),
                        ]),
                        i.IFJMP(),
                        i.PUSHINT_LONG(2078119902n),
                        i.EQUAL(),
                        i.PUSHCONT([
                            i.LDU(64),
                            i.LDGRAMS(),
                            i.ROTREV(),
                            i.BLKDROP2([2 , 1]),
                            i.ADD(),
                            i.XCHG_0(2),
                            i.NEWC(),
                            i.BLKSWAP(3 , 1),
                            i.SWAP2(),
                            i.STGRAMS(),
                            i.ROT(),
                            i.STSLICER(),
                            i.SWAP(),
                            i.STSLICER(),
                            i.ENDC(),
                            i.POPCTR(4),
                        ]),
                        i.IFJMP(),
                        i.BLKDROP(4),
                    ]),
                    i.XCHG_0(2),
                    i.LDUQ(32),
                    i.THROWIFNOT(130),
                    i.PUSH(1),
                    i.PUSHINT_LONG(260734629n),
                    i.EQUAL(),
                    i.IFJMPREF([
                        i.POP(1),
                        i.LDU(64),
                        i.LDGRAMS(),
                        i.LDMSGADDR(),
                        i.PUSH(0),
                        i.PLDU(2),
                        i.NEQINT(0),
                        i.PUSHCONT_SHORT([
                            i.LDMSGADDR(),
                            i.SWAP(),
                        ]),
                        i.PUSHCONT_SHORT([
                            i.PUSHINT(2),
                            i.SDSKIPFIRST(),
                            i.PUSHNULL(),
                        ]),
                        i.IFELSE(),
                        i.SWAP(),
                        i.LDI(1),
                        i.SWAP(),
                        i.PUSHCONT_SHORT([
                            i.LDREF(),
                        ]),
                        i.PUSHCONT_SHORT([
                            i.PUSHNULL(),
                            i.SWAP(),
                        ]),
                        i.IFELSE(),
                        i.LDGRAMS(),
                        i.XCPU(6 , 6),
                        i.XCHG_3([1, 6]),
                        i.XCHG_3([1, 5]),
                        i.XCHG_3([1, 4]),
                        i.XCHG3(3 , 3 , 0),
                        i.POP(2),
                        i.POP(6),
                        i.PUSH(2),
                        i.REWRITESTDADDR(),
                        i.POP(0),
                        i.EQINT(0),
                        i.THROWIFNOT(333),
                        i.GETGLOB(2),
                        i.PUXC(8 , -1),
                        i.SDEQ(),
                        i.THROWIFNOT(705),
                        i.XCPU(6 , 3),
                        i.SUB(),
                        i.PUSH(0),
                        i.GTINT(-1),
                        i.THROWIFNOT(706),
                        i.PUSH(6),
                        i.SBITS(),
                        i.GTINT(0),
                        i.THROWIFNOT(708),
                        i.GETGLOB(1),
                        i.UNTUPLE(4),
                        i.PUSH(9),
                        i.INC(),
                        i.PUSHINT(1),
                        i.AND(),
                        i.XCHG3(4 , 3 , 0),
                        i.PUXC(4 , 3),
                        i.LDMSGADDR(),
                        i.LDGRAMS(),
                        i.PUSHINT(1),
                        i.SDSKIPFIRST(),
                        i.LDGRAMS(),
                        i.LDGRAMS(),
                        i.POP(0),
                        i.BLKDROP2([6 , 1]),
                        i.PUSHINT(0),
                        i.GETORIGINALFWDFEE(),
                        i.MUL(),
                        i.PUXC(7 , -1),
                        i.ADD(),
                        i.PUSHINT_LONG(40000000n),
                        i.ADD(),
                        i.GREATER(),
                        i.THROWIFNOT(709),
                        i.XCHG2(4 , 3),
                        i.PUSHINT(0),
                        i.PUSHINT_8(64),
                        i.PSEUDO_PUSHREF([
                            i.PUSHINT(-1),
                            i.PUSH(10),
                            i.XCHG3(8 , 1 , 3),
                            i.XCHG2(9 , 10),
                            i.NEWC(),
                            i.BLKSWAP(6 , 1),
                            i.PUSHINT_LONG(395134233n),
                            i.XCHG2(0 , 7),
                            i.STU(32),
                            i.XCHG_3([1, 5]),
                            i.STU(64),
                            i.XCHG2(0 , 3),
                            i.STGRAMS(),
                            i.SWAP(),
                            i.STSLICER(),
                            i.SWAP(),
                            i.PUSH(0),
                            i.ISNULL(),
                            i.PUSHCONT_SHORT([
                                i.POP(0),
                                i.PUSHINT(0),
                                i.SWAP(),
                                i.STU(2),
                            ]),
                            i.PUSHCONT_SHORT([
                                i.STSLICER(),
                            ]),
                            i.IFELSE(),
                            i.SWAP(),
                            i.STGRAMS(),
                            i.SWAP(),
                            i.STSLICER(),
                            i.ENDC(),
                            i.PUXC(5 , 1),
                            i.PUSH(8),
                            i.GETPARAM(10),
                            i.NEWC(),
                            i.BLKSWAP(3 , 2),
                            i.SWAP2(),
                            i.STGRAMS(),
                            i.ROT(),
                            i.STSLICER(),
                            i.SWAP(),
                            i.STSLICER(),
                            i.ENDC(),
                            i.XCHG_1([5, 6]),
                            i.XCHG_1([3, 6]),
                            i.XCHG_1([4, 5]),
                            i.XCHG_1([2, 4]),
                            i.XCHG_1([2, 3]),
                            i.BLKPUSH([4 , 1]),
                            i.HASHCU(),
                            i.SWAP(),
                            i.HASHCU(),
                            i.SWAP2(),
                            i.CDEPTH(),
                            i.SWAP(),
                            i.CDEPTH(),
                            i.PUSHINT_LONG(131380n),
                            i.NEWC(),
                            i.STU(24),
                            i.STU(16),
                            i.STU(16),
                            i.STU(256),
                            i.STU(256),
                            i.PUSHINT(1),
                            i.HASHEXT(Hash.SHA256),
                            i.XCHG_0(3),
                            i.NEWC(),
                            debug(i.STSLICECONST(i.hex("6_"))),
                            i.STI(1),
                            i.XCHG_3([1, 2]),
                            i.STREF(),
                            i.STREF(),
                            i.STSLICECONST(i.hex("1002_")),
                            i.STU(256),
                            i.SWAP(),
                            i.PSEUDO_PUSHREF([
                                i.STGRAMS(),
                                i.PUSHINT_8(105),
                                i.STZEROES(),
                                i.STSLICECONST(i.hex("8D_")),
                                i.STDICT(),
                                i.ENDC(),
                                i.SWAP(),
                                i.SENDRAWMSG(),
                                i.XCHG_0(2),
                                i.NEWC(),
                                i.BLKSWAP(3 , 1),
                                i.SWAP2(),
                                i.STGRAMS(),
                                i.ROT(),
                                i.STSLICER(),
                                i.SWAP(),
                                i.STSLICER(),
                                i.ENDC(),
                                i.POPCTR(4),
                            ]),
                        ]),
                    ]),
                    i.PUSH(1),
                    i.PUSHINT_LONG(395134233n),
                    i.EQUAL(),
                    i.IFJMPREF([
                        i.POP(1),
                        i.LDU(64),
                        i.LDGRAMS(),
                        i.LDMSGADDR(),
                        i.PUSH(0),
                        i.PLDU(2),
                        i.NEQINT(0),
                        i.PUSHCONT_SHORT([
                            i.LDMSGADDR(),
                            i.SWAP(),
                        ]),
                        i.PUSHCONT_SHORT([
                            i.PUSHINT(2),
                            i.SDSKIPFIRST(),
                            i.PUSHNULL(),
                        ]),
                        i.IFELSE(),
                        i.SWAP(),
                        i.LDGRAMS(),
                        i.XCPU(5 , 5),
                        i.XCHG_3([1, 5]),
                        i.XCHG_3([1, 4]),
                        i.XCHG3(3 , 3 , 0),
                        i.POP(6),
                        i.XCPU(6 , 3),
                        i.ADD(),
                        i.PUSHINT(0),
                        i.PUSH2(3 , 9),
                        i.GETPARAM(10),
                        i.NEWC(),
                        i.BLKSWAP(3 , 2),
                        i.SWAP2(),
                        i.STGRAMS(),
                        i.ROT(),
                        i.STSLICER(),
                        i.SWAP(),
                        i.STSLICER(),
                        i.ENDC(),
                        i.GETGLOB(2),
                        i.REWRITESTDADDR(),
                        i.POP(1),
                        i.ROTREV(),
                        i.PUSH(0),
                        i.HASHCU(),
                        i.PUSH(2),
                        i.HASHCU(),
                        i.SWAP2(),
                        i.CDEPTH(),
                        i.SWAP(),
                        i.CDEPTH(),
                        i.PUSHINT_LONG(131380n),
                        i.NEWC(),
                        i.STU(24),
                        i.STU(16),
                        i.STU(16),
                        i.STU(256),
                        i.STU(256),
                        i.PUSHINT(1),
                        i.HASHEXT(Hash.SHA256),
                        i.SWAP(),
                        i.EQUAL(),
                        i.NOT(),
                        i.PUSHCONT_SHORT([
                            i.GETGLOB(2),
                            i.PUSH(9),
                            i.SDEQ(),
                            i.THROWIFNOT(707),
                        ]),
                        i.IF(),
                        i.GETGLOB(1),
                        i.UNTUPLE(4),
                        i.PUSH(1),
                        i.GETPARAM(7),
                        i.INDEX(0),
                        i.PUSH(1),
                        i.SUB(),
                        i.PUSHINT_LONG(10000000n),
                        i.TUCK(),
                        i.MIN(),
                        i.SUB(),
                        i.PSEUDO_PUSHREF([
                            i.PUSHINT_LONG(15000000n),
                            i.ADD(),
                            i.SUB(),
                            i.PUSH(11),
                            i.GTINT(0),
                            i.PUSHCONT([
                                i.BLKSWAP(4 , 1),
                                i.LDMSGADDR(),
                                i.LDGRAMS(),
                                i.PUSHINT(1),
                                i.SDSKIPFIRST(),
                                i.LDGRAMS(),
                                i.LDGRAMS(),
                                i.POP(0),
                                i.BLKDROP2([6 , 1]),
                                i.PUSHINT(0),
                                i.GETORIGINALFWDFEE(),
                                i.PUXC(8 , -1),
                                i.ADD(),
                                i.SUB(),
                                i.PUSHINT(1),
                                i.PUSHINT(0),
                                i.PUSH(7),
                                i.XCHG3(7 , 1 , 3),
                                i.XCHG2(6 , 9),
                                i.NEWC(),
                                i.BLKSWAP(4 , 1),
                                i.PUSHINT_LONG(1935855772n),
                                i.XCHG2(0 , 5),
                                i.STU(32),
                                i.XCHG_3([1, 3]),
                                i.STU(64),
                                i.SWAP(),
                                i.STGRAMS(),
                                i.SWAP(),
                                i.STSLICER(),
                                i.SWAP(),
                                i.STSLICER(),
                                i.ENDC(),
                                i.PUSH(8),
                                i.XCHG_0(4),
                                i.XCHG_1([3, 8]),
                                i.XCHG3(5 , 0 , 0),
                                i.XCHG3(4 , 1 , 3),
                                i.ROTREV(),
                                i.NEWC(),
                                i.STSLICECONST(i.hex("6_")),
                                i.STI(1),
                                i.STSLICECONST(i.hex("1_")),
                                i.STSLICE(),
                                i.SWAP(),
                                i.STGRAMS(),
                                i.PUSHINT_8(106),
                                i.STZEROES(),
                                i.STDICT(),
                                i.ENDC(),
                                i.SWAP(),
                                i.SENDRAWMSG(),
                                i.XCHG_1([2, 3]),
                            ]),
                            i.PUSHCONT_SHORT([
                                i.POP(11),
                                i.BLKDROP(4),
                                i.POP(3),
                                i.POP(4),
                                i.POP(0),
                            ]),
                            i.IFELSE(),
                            i.PUSH(2),
                            i.ISNULL(),
                            i.NOT(),
                            i.PUSHCONT_SHORT([
                                i.PUSH(3),
                                i.GTINT(0),
                            ]),
                            i.PUSHCONT_SHORT([
                                i.PUSHINT(0),
                            ]),
                            i.IFELSE(),
                            i.PUSHCONT_SHORT([
                                i.BLKDROP2([3 , 1]),
                            ]),
                            i.IFREFELSE([
                                i.PUSHINT(2),
                                i.PUSHINT(0),
                                i.XCHG_0(3),
                                i.NEWC(),
                                i.SWAP(),
                                i.PUSHINT_LONG(3576854235n),
                                i.ROT(),
                                i.STU(32),
                                i.STU(64),
                                i.ENDC(),
                                i.XCHG_1([3, 5]),
                                i.XCHG3(1 , 5 , 0),
                                i.XCHG3(4 , 1 , 3),
                                i.ROTREV(),
                                i.NEWC(),
                                i.STSLICECONST(i.hex("6_")),
                                i.STI(1),
                                i.STSLICECONST(i.hex("1_")),
                                i.STSLICE(),
                                i.SWAP(),
                                i.STGRAMS(),
                                i.PUSHINT_8(106),
                                i.STZEROES(),
                                i.STDICT(),
                                i.ENDC(),
                                i.SWAP(),
                                i.SENDRAWMSG(),
                            ]),
                            i.XCHG_0(2),
                            i.PSEUDO_PUSHREF([
                                i.NEWC(),
                                i.BLKSWAP(3 , 1),
                                i.SWAP2(),
                                i.STGRAMS(),
                                i.ROT(),
                                i.STSLICER(),
                                i.SWAP(),
                                i.STSLICER(),
                                i.ENDC(),
                                i.POPCTR(4),
                            ]),
                        ]),
                    ]),
                    i.SWAP(),
                    i.PUSHINT_LONG(1499400124n),
                    i.EQUAL(),
                    i.PSEUDO_PUSHREF([
                        i.IFJMPREF([
                            i.LDU(64),
                            i.LDGRAMS(),
                            i.LDMSGADDR(),
                            i.LDI(1),
                            i.SWAP(),
                            i.PUSHCONT_SHORT([
                                i.LDREF(),
                            ]),
                            i.PUSHCONT_SHORT([
                                i.PUSHNULL(),
                                i.SWAP(),
                            ]),
                            i.IFELSE(),
                            i.BLKSWAP(4 , 1),
                            i.POP(0),
                            i.POP(3),
                            i.GETGLOB(2),
                            i.PUXC(5 , -1),
                            i.SDEQ(),
                            i.THROWIFNOT(705),
                            i.XCPU(3 , 3),
                            i.SUB(),
                            i.PUSH(0),
                            i.GTINT(-1),
                            i.THROWIFNOT(706),
                            i.GETGLOB(1),
                            i.UNTUPLE(4),
                            i.XCHG3(3 , 3 , 0),
                            i.PUXC(3 , -1),
                            i.LDMSGADDR(),
                            i.LDGRAMS(),
                            i.PUSHINT(1),
                            i.SDSKIPFIRST(),
                            i.LDGRAMS(),
                            i.LDGRAMS(),
                            i.POP(0),
                            i.BLKDROP2([6 , 1]),
                            i.PUSHINT(0),
                            i.GETORIGINALFWDFEE(),
                            i.PUSHINT_LONG(30000000n),
                            i.ADD(),
                            i.GREATER(),
                            i.THROWIFNOT(707),
                            i.PUSHINT(0),
                            i.PUSHINT_8(64),
                            i.XC2PU(3 , 5 , 6),
                            i.PUSHINT(-1),
                            i.XCHG_0(6),
                            i.NEWC(),
                            i.BLKSWAP(4 , 1),
                            i.PUSHINT_LONG(2078119902n),
                            i.XCHG2(0 , 5),
                            i.STU(32),
                            i.XCHG_3([1, 3]),
                            i.STU(64),
                            i.SWAP(),
                            i.STGRAMS(),
                            i.SWAP(),
                            i.STSLICER(),
                            i.SWAP(),
                            i.STSLICER(),
                            i.ENDC(),
                            i.PUSH(6),
                            i.XCHG3(5 , 4 , 4),
                            i.XCHG3(4 , 1 , 3),
                            i.ROTREV(),
                            i.NEWC(),
                            i.STSLICECONST(i.hex("6_")),
                            i.STI(1),
                            i.STSLICECONST(i.hex("1_")),
                            i.STSLICE(),
                            i.SWAP(),
                            i.STGRAMS(),
                            i.PUSHINT_8(106),
                            i.PSEUDO_PUSHREF([
                                i.STZEROES(),
                                i.STDICT(),
                                i.ENDC(),
                                i.SWAP(),
                                i.SENDRAWMSG(),
                                i.XCHG_0(2),
                                i.NEWC(),
                                i.BLKSWAP(3 , 1),
                                i.SWAP2(),
                                i.STGRAMS(),
                                i.ROT(),
                                i.STSLICER(),
                                i.SWAP(),
                                i.STSLICER(),
                                i.ENDC(),
                                i.POPCTR(4),
                            ]),
                        ]),
                        i.BLKDROP(4),
                        i.THROW(130),
                    ]),
                ]),
            ]),
            i.IFNOTJMP(),
            i.PUSHDICTCONST(new Map([
                [97026, [
                    i.PUSHCTR(4),
                    i.CTOS(),
                    i.LDGRAMS(),
                    i.LDMSGADDR(),
                    i.LDMSGADDR(),
                    i.BLKSWAP(3 , 1),
                    i.BLKDROP2([1 , 3]),
                    i.GETPARAM(10),
                    i.PU2XC(3 , 2 , -2),
                    i.PUXC(3 , -1),
                    i.BLKDROP2([3 , 4]),
                ]],
            ])),
            i.DICTIGETJMPZ(),
            i.THROWARG(11),
        ];

        const blockchain: Blockchain = await Blockchain.create()
        // blockchain.verbosity.vmLogs = "vm_logs_verbose"
        const treasure: SandboxContract<TreasuryContract> = await blockchain.treasury("treasure")

        const code = compileCell(instructions)
        const boc = code.toBoc()
        console.log(code)

        const init: StateInit = {
            code: code,

            // balance: Int as coins,
            //     owner: Address,
            //     master: Address,
            // data: beginCell().storeUint(1, 1).storeInt(123, 32).storeInt(456, 32).endCell(),
            data: beginCell()
                .storeVarInt(0, 16)
                .storeAddress(address("Ef9KEg3X-pNUa8F8OpXU6udobGCbERpEf2_U5MI53YyiFlip"))
                .storeAddress(address("Ef9KEg3X-pNUa8F8OpXU6udobGCbERpEf2_U5MI53YyiFlip"))
                .endCell(),
        }

        const address1 = contractAddress(0, init)
        const contract = new TestContract(address1, init)

        const openContract = blockchain.openContract(contract)

        // Deploy
        await openContract.send(treasure.getSender(), {
            value: toNano("10"),
        }, beginCell()
            .storeVarInt(0, 16)
            .storeAddress(address("Ef9KEg3X-pNUa8F8OpXU6udobGCbERpEf2_U5MI53YyiFlip"))
            .storeAddress(address("Ef9KEg3X-pNUa8F8OpXU6udobGCbERpEf2_U5MI53YyiFlip"))
            .endCell())

        // // send an Add message
        // await openContract.send( treasure.getSender(), {
        //     value: toNano("10"),
        // }, beginCell()
        //     .storeUint(2335447074, 32)
        //     .storeUint(1, 64) // queryId
        //     .storeUint(100, 32) // amount
        //     .endCell()
        // )

        const res = await openContract.getGetWalletData()
        console.log(res.balance)
        console.log(res.owner)

        // const data = await openContract.getAny(65536)
        // const num = data.readBigNumber()
        // expect(Number(num)).toEqual(556)
    })
})

function loadGetterTupleJettonWalletData(source: TupleReader) {
    const _balance = source.readBigNumber();
    const _owner = source.readCell();
    const _master = source.readCell();
    const _code = source.readCell();
    return { $$type: 'JettonWalletData' as const, balance: _balance, owner: _owner, master: _master, code: _code };
}

export class TestContract implements Contract {
    readonly address: Address
    readonly init?: StateInit

    constructor(address: Address, init?: StateInit) {
        this.address = address
        this.init = init
    }

    async send(provider: ContractProvider, via: Sender, args: { value: bigint, bounce?: boolean| null | undefined }, body: Cell) {
        await provider.internal(via, { ...args, body: body });
    }

    async getAny(provider: ContractProvider, id: number): Promise<TupleReader> {
        const builder = new TupleBuilder()
        return (await provider.get(id as any, builder.build())).stack
    }

    async getGetWalletData(provider: ContractProvider) {
        const builder = new TupleBuilder();
        const source = (await provider.get(97026 as any, builder.build())).stack;
        const result = loadGetterTupleJettonWalletData(source);
        return result;
    }
}
