import {
    createSimpleInstr,
    createUnaryInstr,
    createBinaryInstr,
    createTernaryInstr,
    createFixedRangeInstr,
} from "./instr";
import {
    uint,
    int,
    hash,
    tinyInt,
    plduzArg,
    xchgArgs,
    minusOne,
    delta,
    seq2,
    stack,
    control,
    s1,
} from "./asm1";

export const PUSHNAN = () => createSimpleInstr(0x83ff, 16);
export const ADD = () => createSimpleInstr(0xa0, 8);
export const SUB = () => createSimpleInstr(0xa1, 8);
export const SUBR = () => createSimpleInstr(0xa2, 8);
export const NEGATE = () => createSimpleInstr(0xa3, 8);
export const INC = () => createSimpleInstr(0xa4, 8);
export const DEC = () => createSimpleInstr(0xa5, 8);
export const MUL = () => createSimpleInstr(0xa8, 8);
export const POW2 = () => createSimpleInstr(0xae, 8);
export const AND = () => createSimpleInstr(0xb0, 8);
export const OR = () => createSimpleInstr(0xb1, 8);
export const XOR = () => createSimpleInstr(0xb2, 8);
export const NOT = () => createSimpleInstr(0xb3, 8);
export const FITSX = () => createSimpleInstr(0xb600, 16);
export const UFITSX = () => createSimpleInstr(0xb601, 16);
export const BITSIZE = () => createSimpleInstr(0xb602, 16);
export const UBITSIZE = () => createSimpleInstr(0xb603, 16);
export const MIN = () => createSimpleInstr(0xb608, 16);
export const MAX = () => createSimpleInstr(0xb609, 16);
export const MINMAX = () => createSimpleInstr(0xb60a, 16);
export const ABS = () => createSimpleInstr(0xb60b, 16);
export const QADD = () => createSimpleInstr(0xb7a0, 16);
export const QSUB = () => createSimpleInstr(0xb7a1, 16);
export const QSUBR = () => createSimpleInstr(0xb7a2, 16);
export const QNEGATE = () => createSimpleInstr(0xb7a3, 16);
export const QINC = () => createSimpleInstr(0xb7a4, 16);
export const QDEC = () => createSimpleInstr(0xb7a5, 16);
export const QMUL = () => createSimpleInstr(0xb7a8, 16);
export const QPOW2 = () => createSimpleInstr(0xb7ae, 16);
export const QAND = () => createSimpleInstr(0xb7b0, 16);
export const QOR = () => createSimpleInstr(0xb7b1, 16);
export const QXOR = () => createSimpleInstr(0xb7b2, 16);
export const QNOT = () => createSimpleInstr(0xb7b3, 16);
export const QFITSX = () => createSimpleInstr(0xb7b600, 24);
export const QUFITSX = () => createSimpleInstr(0xb7b601, 24);
export const QBITSIZE = () => createSimpleInstr(0xb7b602, 24);
export const QUBITSIZE = () => createSimpleInstr(0xb7b603, 24);
export const QMIN = () => createSimpleInstr(0xb7b608, 24);
export const QMAX = () => createSimpleInstr(0xb7b609, 24);
export const QMINMAX = () => createSimpleInstr(0xb7b60a, 24);
export const QABS = () => createSimpleInstr(0xb7b60b, 24);
export const SGN = () => createSimpleInstr(0xb8, 8);
export const LESS = () => createSimpleInstr(0xb9, 8);
export const EQUAL = () => createSimpleInstr(0xba, 8);
export const LEQ = () => createSimpleInstr(0xbb, 8);
export const GREATER = () => createSimpleInstr(0xbc, 8);
export const NEQ = () => createSimpleInstr(0xbd, 8);
export const GEQ = () => createSimpleInstr(0xbe, 8);
export const CMP = () => createSimpleInstr(0xbf, 8);
export const ISNAN = () => createSimpleInstr(0xc4, 8);
export const CHKNAN = () => createSimpleInstr(0xc5, 8);
export const QSGN = () => createSimpleInstr(0xb7b8, 16);
export const QLESS = () => createSimpleInstr(0xb7b9, 16);
export const QEQUAL = () => createSimpleInstr(0xb7ba, 16);
export const QLEQ = () => createSimpleInstr(0xb7bb, 16);
export const QGREATER = () => createSimpleInstr(0xb7bc, 16);
export const QNEQ = () => createSimpleInstr(0xb7bd, 16);
export const QGEQ = () => createSimpleInstr(0xb7be, 16);
export const QCMP = () => createSimpleInstr(0xb7bf, 16);
export const SEMPTY = () => createSimpleInstr(0xc700, 16);
export const SDEMPTY = () => createSimpleInstr(0xc701, 16);
export const SREMPTY = () => createSimpleInstr(0xc702, 16);
export const SDFIRST = () => createSimpleInstr(0xc703, 16);
export const SDLEXCMP = () => createSimpleInstr(0xc704, 16);
export const SDEQ = () => createSimpleInstr(0xc705, 16);
export const SDPFX = () => createSimpleInstr(0xc708, 16);
export const SDPFXREV = () => createSimpleInstr(0xc709, 16);
export const SDPPFX = () => createSimpleInstr(0xc70a, 16);
export const SDPPFXREV = () => createSimpleInstr(0xc70b, 16);
export const SDSFX = () => createSimpleInstr(0xc70c, 16);
export const SDSFXREV = () => createSimpleInstr(0xc70d, 16);
export const SDPSFX = () => createSimpleInstr(0xc70e, 16);
export const SDPSFXREV = () => createSimpleInstr(0xc70f, 16);
export const SDCNTLEAD0 = () => createSimpleInstr(0xc710, 16);
export const SDCNTLEAD1 = () => createSimpleInstr(0xc711, 16);
export const SDCNTTRAIL0 = () => createSimpleInstr(0xc712, 16);
export const SDCNTTRAIL1 = () => createSimpleInstr(0xc713, 16);
export const NEWC = () => createSimpleInstr(0xc8, 8);
export const ENDC = () => createSimpleInstr(0xc9, 8);
export const ENDCST = () => createSimpleInstr(0xcd, 8);
export const STBREF = () => createSimpleInstr(0xcf11, 16);
export const STB = () => createSimpleInstr(0xcf13, 16);
export const STREFR = () => createSimpleInstr(0xcf14, 16);
export const STBREFR = () => createSimpleInstr(0xcf15, 16);
export const STSLICER = () => createSimpleInstr(0xcf16, 16);
export const STBR = () => createSimpleInstr(0xcf17, 16);
export const STREFQ = () => createSimpleInstr(0xcf18, 16);
export const STBREFQ = () => createSimpleInstr(0xcf19, 16);
export const STSLICEQ = () => createSimpleInstr(0xcf1a, 16);
export const STBQ = () => createSimpleInstr(0xcf1b, 16);
export const STREFRQ = () => createSimpleInstr(0xcf1c, 16);
export const STBREFRQ = () => createSimpleInstr(0xcf1d, 16);
export const STSLICERQ = () => createSimpleInstr(0xcf1e, 16);
export const STBRQ = () => createSimpleInstr(0xcf1f, 16);
export const ENDXC = () => createSimpleInstr(0xcf23, 16);
export const BDEPTH = () => createSimpleInstr(0xcf30, 16);
export const BBITS = () => createSimpleInstr(0xcf31, 16);
export const BREFS = () => createSimpleInstr(0xcf32, 16);
export const BBITREFS = () => createSimpleInstr(0xcf33, 16);
export const BREMBITS = () => createSimpleInstr(0xcf35, 16);
export const BREMREFS = () => createSimpleInstr(0xcf36, 16);
export const BREMBITREFS = () => createSimpleInstr(0xcf37, 16);
export const BCHKREFS = () => createSimpleInstr(0xcf3a, 16);
export const BCHKBITREFS = () => createSimpleInstr(0xcf3b, 16);
export const BCHKREFSQ = () => createSimpleInstr(0xcf3e, 16);
export const BCHKBITREFSQ = () => createSimpleInstr(0xcf3f, 16);
export const STZEROES = () => createSimpleInstr(0xcf40, 16);
export const STONES = () => createSimpleInstr(0xcf41, 16);
export const STSAME = () => createSimpleInstr(0xcf42, 16);
export const CTOS = () => createSimpleInstr(0xd0, 8);
export const ENDS = () => createSimpleInstr(0xd1, 8);
export const LDREF = () => createSimpleInstr(0xd4, 8);
export const LDREFRTOS = () => createSimpleInstr(0xd5, 8);
export const SDCUTFIRST = () => createSimpleInstr(0xd720, 16);
export const SDSKIPFIRST = () => createSimpleInstr(0xd721, 16);
export const SDCUTLAST = () => createSimpleInstr(0xd722, 16);
export const SDSKIPLAST = () => createSimpleInstr(0xd723, 16);
export const SDSUBSTR = () => createSimpleInstr(0xd724, 16);
export const SDBEGINSX = () => createSimpleInstr(0xd726, 16);
export const SDBEGINSXQ = () => createSimpleInstr(0xd727, 16);
export const SCUTFIRST = () => createSimpleInstr(0xd730, 16);
export const SSKIPFIRST = () => createSimpleInstr(0xd731, 16);
export const SCUTLAST = () => createSimpleInstr(0xd732, 16);
export const SSKIPLAST = () => createSimpleInstr(0xd733, 16);
export const SUBSLICE = () => createSimpleInstr(0xd734, 16);
export const SPLIT = () => createSimpleInstr(0xd736, 16);
export const SPLITQ = () => createSimpleInstr(0xd737, 16);
export const XCTOS = () => createSimpleInstr(0xd739, 16);
export const XLOAD = () => createSimpleInstr(0xd73a, 16);
export const XLOADQ = () => createSimpleInstr(0xd73b, 16);
export const SCHKBITS = () => createSimpleInstr(0xd741, 16);
export const SCHKREFS = () => createSimpleInstr(0xd742, 16);
export const SCHKBITREFS = () => createSimpleInstr(0xd743, 16);
export const SCHKBITSQ = () => createSimpleInstr(0xd745, 16);
export const SCHKREFSQ = () => createSimpleInstr(0xd746, 16);
export const SCHKBITREFSQ = () => createSimpleInstr(0xd747, 16);
export const PLDREFVAR = () => createSimpleInstr(0xd748, 16);
export const SBITS = () => createSimpleInstr(0xd749, 16);
export const SREFS = () => createSimpleInstr(0xd74a, 16);
export const SBITREFS = () => createSimpleInstr(0xd74b, 16);
export const LDZEROES = () => createSimpleInstr(0xd760, 16);
export const LDONES = () => createSimpleInstr(0xd761, 16);
export const LDSAME = () => createSimpleInstr(0xd762, 16);
export const SDEPTH = () => createSimpleInstr(0xd764, 16);
export const CDEPTH = () => createSimpleInstr(0xd765, 16);
export const CLEVEL = () => createSimpleInstr(0xd766, 16);
export const CLEVELMASK = () => createSimpleInstr(0xd767, 16);
export const CHASHIX = () => createSimpleInstr(0xd770, 16);
export const CDEPTHIX = () => createSimpleInstr(0xd771, 16);
export const EXECUTE = () => createSimpleInstr(0xd8, 8);
export const JMPX = () => createSimpleInstr(0xd9, 8);
export const RET = () => createSimpleInstr(0xdb30, 16);
export const RETALT = () => createSimpleInstr(0xdb31, 16);
export const RETBOOL = () => createSimpleInstr(0xdb32, 16);
export const CALLCC = () => createSimpleInstr(0xdb34, 16);
export const JMPXDATA = () => createSimpleInstr(0xdb35, 16);
export const CALLXVARARGS = () => createSimpleInstr(0xdb38, 16);
export const RETVARARGS = () => createSimpleInstr(0xdb39, 16);
export const JMPXVARARGS = () => createSimpleInstr(0xdb3a, 16);
export const CALLCCVARARGS = () => createSimpleInstr(0xdb3b, 16);
export const RETDATA = () => createSimpleInstr(0xdb3f, 16);
export const RUNVMX = () => createSimpleInstr(0xdb50, 16);
export const IFRET = () => createSimpleInstr(0xdc, 8);
export const IFNOTRET = () => createSimpleInstr(0xdd, 8);
export const IF = () => createSimpleInstr(0xde, 8);
export const IFNOT = () => createSimpleInstr(0xdf, 8);
export const IFJMP = () => createSimpleInstr(0xe0, 8);
export const IFNOTJMP = () => createSimpleInstr(0xe1, 8);
export const IFELSE = () => createSimpleInstr(0xe2, 8);
export const CONDSEL = () => createSimpleInstr(0xe304, 16);
export const CONDSELCHK = () => createSimpleInstr(0xe305, 16);
export const IFRETALT = () => createSimpleInstr(0xe308, 16);
export const IFNOTRETALT = () => createSimpleInstr(0xe309, 16);
export const REPEAT = () => createSimpleInstr(0xe4, 8);
export const REPEATEND = () => createSimpleInstr(0xe5, 8);
export const UNTIL = () => createSimpleInstr(0xe6, 8);
export const UNTILEND = () => createSimpleInstr(0xe7, 8);
export const WHILE = () => createSimpleInstr(0xe8, 8);
export const WHILEEND = () => createSimpleInstr(0xe9, 8);
export const AGAIN = () => createSimpleInstr(0xea, 8);
export const AGAINEND = () => createSimpleInstr(0xeb, 8);
export const REPEATBRK = () => createSimpleInstr(0xe314, 16);
export const REPEATENDBRK = () => createSimpleInstr(0xe315, 16);
export const UNTILBRK = () => createSimpleInstr(0xe316, 16);
export const UNTILENDBRK = () => createSimpleInstr(0xe317, 16);
export const WHILEBRK = () => createSimpleInstr(0xe318, 16);
export const WHILEENDBRK = () => createSimpleInstr(0xe319, 16);
export const AGAINBRK = () => createSimpleInstr(0xe31a, 16);
export const AGAINENDBRK = () => createSimpleInstr(0xe31b, 16);
export const RETURNVARARGS = () => createSimpleInstr(0xed10, 16);
export const SETCONTVARARGS = () => createSimpleInstr(0xed11, 16);
export const SETNUMVARARGS = () => createSimpleInstr(0xed12, 16);
export const BLESS = () => createSimpleInstr(0xed1e, 16);
export const BLESSVARARGS = () => createSimpleInstr(0xed1f, 16);
export const PUSHCTRX = () => createSimpleInstr(0xede0, 16);
export const POPCTRX = () => createSimpleInstr(0xede1, 16);
export const SETCONTCTRX = () => createSimpleInstr(0xede2, 16);
export const SETCONTCTRMANYX = () => createSimpleInstr(0xede4, 16);
export const BOOLAND = () => createSimpleInstr(0xedf0, 16);
export const BOOLOR = () => createSimpleInstr(0xedf1, 16);
export const COMPOSBOTH = () => createSimpleInstr(0xedf2, 16);
export const ATEXIT = () => createSimpleInstr(0xedf3, 16);
export const ATEXITALT = () => createSimpleInstr(0xedf4, 16);
export const SETEXITALT = () => createSimpleInstr(0xedf5, 16);
export const THENRET = () => createSimpleInstr(0xedf6, 16);
export const THENRETALT = () => createSimpleInstr(0xedf7, 16);
export const INVERT = () => createSimpleInstr(0xedf8, 16);
export const BOOLEVAL = () => createSimpleInstr(0xedf9, 16);
export const SAMEALT = () => createSimpleInstr(0xedfa, 16);
export const SAMEALTSAVE = () => createSimpleInstr(0xedfb, 16);
export const TRY = () => createSimpleInstr(0xf2ff, 16);
export const SETCPX = () => createSimpleInstr(0xfff0, 16);
export const STDICT = () => createSimpleInstr(0xf400, 16);
export const SKIPDICT = () => createSimpleInstr(0xf401, 16);
export const LDDICTS = () => createSimpleInstr(0xf402, 16);
export const PLDDICTS = () => createSimpleInstr(0xf403, 16);
export const LDDICT = () => createSimpleInstr(0xf404, 16);
export const PLDDICT = () => createSimpleInstr(0xf405, 16);
export const LDDICTQ = () => createSimpleInstr(0xf406, 16);
export const PLDDICTQ = () => createSimpleInstr(0xf407, 16);
export const PFXDICTSET = () => createSimpleInstr(0xf470, 16);
export const PFXDICTREPLACE = () => createSimpleInstr(0xf471, 16);
export const PFXDICTADD = () => createSimpleInstr(0xf472, 16);
export const PFXDICTDEL = () => createSimpleInstr(0xf473, 16);
export const PFXDICTGETQ = () => createSimpleInstr(0xf4a8, 16);
export const PFXDICTGET = () => createSimpleInstr(0xf4a9, 16);
export const PFXDICTGETJMP = () => createSimpleInstr(0xf4aa, 16);
export const PFXDICTGETEXEC = () => createSimpleInstr(0xf4ab, 16);
export const NOP = () => createSimpleInstr(0x0, 8);
export const SWAP = () => createSimpleInstr(0x1, 8);
export const DUP = () => createSimpleInstr(0x20, 8);
export const OVER = () => createSimpleInstr(0x21, 8);
export const DROP = () => createSimpleInstr(0x30, 8);
export const NIP = () => createSimpleInstr(0x31, 8);
export const ROT = () => createSimpleInstr(0x58, 8);
export const ROTREV = () => createSimpleInstr(0x59, 8);
export const PICK = () => createSimpleInstr(0x60, 8);
export const ROLL = () => createSimpleInstr(0x61, 8);
export const ROLLREV = () => createSimpleInstr(0x62, 8);
export const BLKSWX = () => createSimpleInstr(0x63, 8);
export const REVX = () => createSimpleInstr(0x64, 8);
export const DROPX = () => createSimpleInstr(0x65, 8);
export const TUCK = () => createSimpleInstr(0x66, 8);
export const XCHGX = () => createSimpleInstr(0x67, 8);
export const DEPTH = () => createSimpleInstr(0x68, 8);
export const CHKDEPTH = () => createSimpleInstr(0x69, 8);
export const ONLYTOPX = () => createSimpleInstr(0x6a, 8);
export const ONLYX = () => createSimpleInstr(0x6b, 8);
export const ACCEPT = () => createSimpleInstr(0xf800, 16);
export const SETGASLIMIT = () => createSimpleInstr(0xf801, 16);
export const GASCONSUMED = () => createSimpleInstr(0xf807, 16);
export const COMMIT = () => createSimpleInstr(0xf80f, 16);
export const NOW = () => createSimpleInstr(0xf823, 16);
export const BLOCKLT = () => createSimpleInstr(0xf824, 16);
export const LTIME = () => createSimpleInstr(0xf825, 16);
export const RANDSEED = () => createSimpleInstr(0xf826, 16);
export const BALANCE = () => createSimpleInstr(0xf827, 16);
export const MYADDR = () => createSimpleInstr(0xf828, 16);
export const CONFIGROOT = () => createSimpleInstr(0xf829, 16);
export const MYCODE = () => createSimpleInstr(0xf82a, 16);
export const INCOMINGVALUE = () => createSimpleInstr(0xf82b, 16);
export const STORAGEFEES = () => createSimpleInstr(0xf82c, 16);
export const PREVBLOCKSINFOTUPLE = () => createSimpleInstr(0xf82d, 16);
export const UNPACKEDCONFIGTUPLE = () => createSimpleInstr(0xf82e, 16);
export const DUEPAYMENT = () => createSimpleInstr(0xf82f, 16);
export const CONFIGDICT = () => createSimpleInstr(0xf830, 16);
export const CONFIGPARAM = () => createSimpleInstr(0xf832, 16);
export const CONFIGOPTPARAM = () => createSimpleInstr(0xf833, 16);
export const PREVMCBLOCKS = () => createSimpleInstr(0xf83400, 24);
export const PREVKEYBLOCK = () => createSimpleInstr(0xf83401, 24);
export const PREVMCBLOCKS_100 = () => createSimpleInstr(0xf83402, 24);
export const GLOBALID = () => createSimpleInstr(0xf835, 16);
export const GETGASFEE = () => createSimpleInstr(0xf836, 16);
export const GETSTORAGEFEE = () => createSimpleInstr(0xf837, 16);
export const GETFORWARDFEE = () => createSimpleInstr(0xf838, 16);
export const GETPRECOMPILEDGAS = () => createSimpleInstr(0xf839, 16);
export const GETORIGINALFWDFEE = () => createSimpleInstr(0xf83a, 16);
export const GETGASFEESIMPLE = () => createSimpleInstr(0xf83b, 16);
export const GETFORWARDFEESIMPLE = () => createSimpleInstr(0xf83c, 16);
export const GETGLOBVAR = () => createSimpleInstr(0xf840, 16);
export const SETGLOBVAR = () => createSimpleInstr(0xf860, 16);
export const RANDU256 = () => createSimpleInstr(0xf810, 16);
export const RAND = () => createSimpleInstr(0xf811, 16);
export const SETRAND = () => createSimpleInstr(0xf814, 16);
export const ADDRAND = () => createSimpleInstr(0xf815, 16);
export const HASHCU = () => createSimpleInstr(0xf900, 16);
export const HASHSU = () => createSimpleInstr(0xf901, 16);
export const SHA256U = () => createSimpleInstr(0xf902, 16);
export const CHKSIGNU = () => createSimpleInstr(0xf910, 16);
export const CHKSIGNS = () => createSimpleInstr(0xf911, 16);
export const ECRECOVER = () => createSimpleInstr(0xf912, 16);
export const SECP256K1_XONLY_PUBKEY_TWEAK_ADD = () => createSimpleInstr(0xf913, 16);
export const P256_CHKSIGNU = () => createSimpleInstr(0xf914, 16);
export const P256_CHKSIGNS = () => createSimpleInstr(0xf915, 16);
export const RIST255_FROMHASH = () => createSimpleInstr(0xf920, 16);
export const RIST255_VALIDATE = () => createSimpleInstr(0xf921, 16);
export const RIST255_ADD = () => createSimpleInstr(0xf922, 16);
export const RIST255_SUB = () => createSimpleInstr(0xf923, 16);
export const RIST255_MUL = () => createSimpleInstr(0xf924, 16);
export const RIST255_MULBASE = () => createSimpleInstr(0xf925, 16);
export const RIST255_PUSHL = () => createSimpleInstr(0xf926, 16);
export const RIST255_QVALIDATE = () => createSimpleInstr(0xb7f921, 24);
export const RIST255_QADD = () => createSimpleInstr(0xb7f922, 24);
export const RIST255_QSUB = () => createSimpleInstr(0xb7f923, 24);
export const RIST255_QMUL = () => createSimpleInstr(0xb7f924, 24);
export const RIST255_QMULBASE = () => createSimpleInstr(0xb7f925, 24);
export const BLS_VERIFY = () => createSimpleInstr(0xf93000, 24);
export const BLS_AGGREGATE = () => createSimpleInstr(0xf93001, 24);
export const BLS_FASTAGGREGATEVERIFY = () => createSimpleInstr(0xf93002, 24);
export const BLS_AGGREGATEVERIFY = () => createSimpleInstr(0xf93003, 24);
export const BLS_G1_ADD = () => createSimpleInstr(0xf93010, 24);
export const BLS_G1_SUB = () => createSimpleInstr(0xf93011, 24);
export const BLS_G1_NEG = () => createSimpleInstr(0xf93012, 24);
export const BLS_G1_MUL = () => createSimpleInstr(0xf93013, 24);
export const BLS_G1_MULTIEXP = () => createSimpleInstr(0xf93014, 24);
export const BLS_G1_ZERO = () => createSimpleInstr(0xf93015, 24);
export const BLS_MAP_TO_G1 = () => createSimpleInstr(0xf93016, 24);
export const BLS_G1_INGROUP = () => createSimpleInstr(0xf93017, 24);
export const BLS_G1_ISZERO = () => createSimpleInstr(0xf93018, 24);
export const BLS_G2_ADD = () => createSimpleInstr(0xf93020, 24);
export const BLS_G2_SUB = () => createSimpleInstr(0xf93021, 24);
export const BLS_G2_NEG = () => createSimpleInstr(0xf93022, 24);
export const BLS_G2_MUL = () => createSimpleInstr(0xf93023, 24);
export const BLS_G2_MULTIEXP = () => createSimpleInstr(0xf93024, 24);
export const BLS_G2_ZERO = () => createSimpleInstr(0xf93025, 24);
export const BLS_MAP_TO_G2 = () => createSimpleInstr(0xf93026, 24);
export const BLS_G2_INGROUP = () => createSimpleInstr(0xf93027, 24);
export const BLS_G2_ISZERO = () => createSimpleInstr(0xf93028, 24);
export const BLS_PAIRING = () => createSimpleInstr(0xf93030, 24);
export const BLS_PUSHR = () => createSimpleInstr(0xf93031, 24);
export const CDATASIZEQ = () => createSimpleInstr(0xf940, 16);
export const CDATASIZE = () => createSimpleInstr(0xf941, 16);
export const SDATASIZEQ = () => createSimpleInstr(0xf942, 16);
export const SDATASIZE = () => createSimpleInstr(0xf943, 16);
export const LDGRAMS = () => createSimpleInstr(0xfa00, 16);
export const LDVARINT16 = () => createSimpleInstr(0xfa01, 16);
export const STGRAMS = () => createSimpleInstr(0xfa02, 16);
export const STVARINT16 = () => createSimpleInstr(0xfa03, 16);
export const LDVARUINT32 = () => createSimpleInstr(0xfa04, 16);
export const LDVARINT32 = () => createSimpleInstr(0xfa05, 16);
export const STVARUINT32 = () => createSimpleInstr(0xfa06, 16);
export const STVARINT32 = () => createSimpleInstr(0xfa07, 16);
export const LDMSGADDR = () => createSimpleInstr(0xfa40, 16);
export const LDMSGADDRQ = () => createSimpleInstr(0xfa41, 16);
export const PARSEMSGADDR = () => createSimpleInstr(0xfa42, 16);
export const PARSEMSGADDRQ = () => createSimpleInstr(0xfa43, 16);
export const REWRITESTDADDR = () => createSimpleInstr(0xfa44, 16);
export const REWRITESTDADDRQ = () => createSimpleInstr(0xfa45, 16);
export const REWRITEVARADDR = () => createSimpleInstr(0xfa46, 16);
export const REWRITEVARADDRQ = () => createSimpleInstr(0xfa47, 16);
export const SENDRAWMSG = () => createSimpleInstr(0xfb00, 16);
export const RAWRESERVE = () => createSimpleInstr(0xfb02, 16);
export const RAWRESERVEX = () => createSimpleInstr(0xfb03, 16);
export const SETCODE = () => createSimpleInstr(0xfb04, 16);
export const SETLIBCODE = () => createSimpleInstr(0xfb06, 16);
export const CHANGELIB = () => createSimpleInstr(0xfb07, 16);
export const SENDMSG = () => createSimpleInstr(0xfb08, 16);
export const PUSHNULL = () => createSimpleInstr(0x6d, 8);
export const ISNULL = () => createSimpleInstr(0x6e, 8);
export const TUPLEVAR = () => createSimpleInstr(0x6f80, 16);
export const INDEXVAR = () => createSimpleInstr(0x6f81, 16);
export const UNTUPLEVAR = () => createSimpleInstr(0x6f82, 16);
export const UNPACKFIRSTVAR = () => createSimpleInstr(0x6f83, 16);
export const EXPLODEVAR = () => createSimpleInstr(0x6f84, 16);
export const SETINDEXVAR = () => createSimpleInstr(0x6f85, 16);
export const INDEXVARQ = () => createSimpleInstr(0x6f86, 16);
export const SETINDEXVARQ = () => createSimpleInstr(0x6f87, 16);
export const TLEN = () => createSimpleInstr(0x6f88, 16);
export const QTLEN = () => createSimpleInstr(0x6f89, 16);
export const ISTUPLE = () => createSimpleInstr(0x6f8a, 16);
export const LAST = () => createSimpleInstr(0x6f8b, 16);
export const TPUSH = () => createSimpleInstr(0x6f8c, 16);
export const TPOP = () => createSimpleInstr(0x6f8d, 16);
export const NULLSWAPIF = () => createSimpleInstr(0x6fa0, 16);
export const NULLSWAPIFNOT = () => createSimpleInstr(0x6fa1, 16);
export const NULLROTRIF = () => createSimpleInstr(0x6fa2, 16);
export const NULLROTRIFNOT = () => createSimpleInstr(0x6fa3, 16);
export const NULLSWAPIF2 = () => createSimpleInstr(0x6fa4, 16);
export const NULLSWAPIFNOT2 = () => createSimpleInstr(0x6fa5, 16);
export const NULLROTRIF2 = () => createSimpleInstr(0x6fa6, 16);
export const NULLROTRIFNOT2 = () => createSimpleInstr(0x6fa7, 16);
export const ADDDIVMOD = () => createSimpleInstr(0xa900, 16);
export const ADDDIVMODR = () => createSimpleInstr(0xa901, 16);
export const ADDDIVMODC = () => createSimpleInstr(0xa902, 16);
export const DIV = () => createSimpleInstr(0xa904, 16);
export const DIVR = () => createSimpleInstr(0xa905, 16);
export const DIVC = () => createSimpleInstr(0xa906, 16);
export const MOD = () => createSimpleInstr(0xa908, 16);
export const MODR = () => createSimpleInstr(0xa909, 16);
export const MODC = () => createSimpleInstr(0xa90a, 16);
export const DIVMOD = () => createSimpleInstr(0xa90c, 16);
export const DIVMODR = () => createSimpleInstr(0xa90d, 16);
export const DIVMODC = () => createSimpleInstr(0xa90e, 16);
export const QADDDIVMOD = () => createSimpleInstr(0xb7a900, 24);
export const QADDDIVMODR = () => createSimpleInstr(0xb7a901, 24);
export const QADDDIVMODC = () => createSimpleInstr(0xb7a902, 24);
export const QDIV = () => createSimpleInstr(0xb7a904, 24);
export const QDIVR = () => createSimpleInstr(0xb7a905, 24);
export const QDIVC = () => createSimpleInstr(0xb7a906, 24);
export const QMOD = () => createSimpleInstr(0xb7a908, 24);
export const QMODR = () => createSimpleInstr(0xb7a909, 24);
export const QMODC = () => createSimpleInstr(0xb7a90a, 24);
export const QDIVMOD = () => createSimpleInstr(0xb7a90c, 24);
export const QDIVMODR = () => createSimpleInstr(0xb7a90d, 24);
export const QDIVMODC = () => createSimpleInstr(0xb7a90e, 24);
export const ADDRSHIFTMOD = () => createSimpleInstr(0xa920, 16);
export const ADDRSHIFTMODR = () => createSimpleInstr(0xa921, 16);
export const ADDRSHIFTMODC = () => createSimpleInstr(0xa922, 16);
export const RSHIFTR = () => createSimpleInstr(0xa925, 16);
export const RSHIFTC = () => createSimpleInstr(0xa926, 16);
export const MODPOW2 = () => createSimpleInstr(0xa928, 16);
export const MODPOW2R = () => createSimpleInstr(0xa929, 16);
export const MODPOW2C = () => createSimpleInstr(0xa92a, 16);
export const RSHIFTMOD = () => createSimpleInstr(0xa92c, 16);
export const RSHIFTMODR = () => createSimpleInstr(0xa92d, 16);
export const RSHIFTMODC = () => createSimpleInstr(0xa92e, 16);
export const QADDRSHIFTMOD = () => createSimpleInstr(0xb7a920, 24);
export const QADDRSHIFTMODR = () => createSimpleInstr(0xb7a921, 24);
export const QADDRSHIFTMODC = () => createSimpleInstr(0xb7a922, 24);
export const QRSHIFTR = () => createSimpleInstr(0xb7a925, 24);
export const QRSHIFTC = () => createSimpleInstr(0xb7a926, 24);
export const QMODPOW2 = () => createSimpleInstr(0xb7a928, 24);
export const QMODPOW2R = () => createSimpleInstr(0xb7a929, 24);
export const QMODPOW2C = () => createSimpleInstr(0xb7a92a, 24);
export const QRSHIFTMOD = () => createSimpleInstr(0xb7a92c, 24);
export const QRSHIFTMODR = () => createSimpleInstr(0xb7a92d, 24);
export const QRSHIFTMODC = () => createSimpleInstr(0xb7a92e, 24);
export const MULADDDIVMOD = () => createSimpleInstr(0xa980, 16);
export const MULADDDIVMODR = () => createSimpleInstr(0xa981, 16);
export const MULADDDIVMODC = () => createSimpleInstr(0xa982, 16);
export const MULDIV = () => createSimpleInstr(0xa984, 16);
export const MULDIVR = () => createSimpleInstr(0xa985, 16);
export const MULDIVC = () => createSimpleInstr(0xa986, 16);
export const MULMOD = () => createSimpleInstr(0xa988, 16);
export const MULMODR = () => createSimpleInstr(0xa989, 16);
export const MULMODC = () => createSimpleInstr(0xa98a, 16);
export const MULDIVMOD = () => createSimpleInstr(0xa98c, 16);
export const MULDIVMODR = () => createSimpleInstr(0xa98d, 16);
export const MULDIVMODC = () => createSimpleInstr(0xa98e, 16);
export const QMULADDDIVMOD = () => createSimpleInstr(0xb7a980, 24);
export const QMULADDDIVMODR = () => createSimpleInstr(0xb7a981, 24);
export const QMULADDDIVMODC = () => createSimpleInstr(0xb7a982, 24);
export const QMULDIV = () => createSimpleInstr(0xb7a984, 24);
export const QMULDIVR = () => createSimpleInstr(0xb7a985, 24);
export const QMULDIVC = () => createSimpleInstr(0xb7a986, 24);
export const QMULMOD = () => createSimpleInstr(0xb7a988, 24);
export const QMULMODR = () => createSimpleInstr(0xb7a989, 24);
export const QMULMODC = () => createSimpleInstr(0xb7a98a, 24);
export const QMULDIVMOD = () => createSimpleInstr(0xb7a98c, 24);
export const QMULDIVMODR = () => createSimpleInstr(0xb7a98d, 24);
export const QMULDIVMODC = () => createSimpleInstr(0xb7a98e, 24);
export const MULADDRSHIFTMOD = () => createSimpleInstr(0xa9a0, 16);
export const MULADDRSHIFTRMOD = () => createSimpleInstr(0xa9a1, 16);
export const MULADDRSHIFTCMOD = () => createSimpleInstr(0xa9a2, 16);
export const MULRSHIFT = () => createSimpleInstr(0xa9a4, 16);
export const MULRSHIFTR = () => createSimpleInstr(0xa9a5, 16);
export const MULRSHIFTC = () => createSimpleInstr(0xa9a6, 16);
export const MULMODPOW2 = () => createSimpleInstr(0xa9a8, 16);
export const MULMODPOW2R = () => createSimpleInstr(0xa9a9, 16);
export const MULMODPOW2C = () => createSimpleInstr(0xa9aa, 16);
export const MULRSHIFTMOD = () => createSimpleInstr(0xa9ac, 16);
export const MULRSHIFTRMOD = () => createSimpleInstr(0xa9ad, 16);
export const MULRSHIFTCMOD = () => createSimpleInstr(0xa9ae, 16);
export const QMULADDRSHIFTMOD = () => createSimpleInstr(0xb7a9a0, 24);
export const QMULADDRSHIFTRMOD = () => createSimpleInstr(0xb7a9a1, 24);
export const QMULADDRSHIFTCMOD = () => createSimpleInstr(0xb7a9a2, 24);
export const QMULRSHIFT = () => createSimpleInstr(0xb7a9a4, 24);
export const QMULRSHIFTR = () => createSimpleInstr(0xb7a9a5, 24);
export const QMULRSHIFTC = () => createSimpleInstr(0xb7a9a6, 24);
export const QMULMODPOW2 = () => createSimpleInstr(0xb7a9a8, 24);
export const QMULMODPOW2R = () => createSimpleInstr(0xb7a9a9, 24);
export const QMULMODPOW2C = () => createSimpleInstr(0xb7a9aa, 24);
export const QMULRSHIFTMOD = () => createSimpleInstr(0xb7a9ac, 24);
export const QMULRSHIFTRMOD = () => createSimpleInstr(0xb7a9ad, 24);
export const QMULRSHIFTCMOD = () => createSimpleInstr(0xb7a9ae, 24);
export const LSHIFTADDDIVMOD = () => createSimpleInstr(0xa9c0, 16);
export const LSHIFTADDDIVMODR = () => createSimpleInstr(0xa9c1, 16);
export const LSHIFTADDDIVMODC = () => createSimpleInstr(0xa9c2, 16);
export const LSHIFTDIV = () => createSimpleInstr(0xa9c4, 16);
export const LSHIFTDIVR = () => createSimpleInstr(0xa9c5, 16);
export const LSHIFTDIVC = () => createSimpleInstr(0xa9c6, 16);
export const LSHIFTMOD = () => createSimpleInstr(0xa9c8, 16);
export const LSHIFTMODR = () => createSimpleInstr(0xa9c9, 16);
export const LSHIFTMODC = () => createSimpleInstr(0xa9ca, 16);
export const LSHIFTDIVMOD = () => createSimpleInstr(0xa9cc, 16);
export const LSHIFTDIVMODR = () => createSimpleInstr(0xa9cd, 16);
export const LSHIFTDIVMODC = () => createSimpleInstr(0xa9ce, 16);
export const QLSHIFTADDDIVMOD = () => createSimpleInstr(0xb7a9c0, 24);
export const QLSHIFTADDDIVMODR = () => createSimpleInstr(0xb7a9c1, 24);
export const QLSHIFTADDDIVMODC = () => createSimpleInstr(0xb7a9c2, 24);
export const QLSHIFTDIV = () => createSimpleInstr(0xb7a9c4, 24);
export const QLSHIFTDIVR = () => createSimpleInstr(0xb7a9c5, 24);
export const QLSHIFTDIVC = () => createSimpleInstr(0xb7a9c6, 24);
export const QLSHIFTMOD = () => createSimpleInstr(0xb7a9c8, 24);
export const QLSHIFTMODR = () => createSimpleInstr(0xb7a9c9, 24);
export const QLSHIFTMODC = () => createSimpleInstr(0xb7a9ca, 24);
export const QLSHIFTDIVMOD = () => createSimpleInstr(0xb7a9cc, 24);
export const QLSHIFTDIVMODR = () => createSimpleInstr(0xb7a9cd, 24);
export const QLSHIFTDIVMODC = () => createSimpleInstr(0xb7a9ce, 24);
export const STIX = () => createSimpleInstr(0xcf00, 16);
export const STUX = () => createSimpleInstr(0xcf01, 16);
export const STIXR = () => createSimpleInstr(0xcf02, 16);
export const STUXR = () => createSimpleInstr(0xcf03, 16);
export const STIXQ = () => createSimpleInstr(0xcf04, 16);
export const STUXQ = () => createSimpleInstr(0xcf05, 16);
export const STIXRQ = () => createSimpleInstr(0xcf06, 16);
export const STUXRQ = () => createSimpleInstr(0xcf07, 16);
export const STILE4 = () => createSimpleInstr(0xcf28, 16);
export const STULE4 = () => createSimpleInstr(0xcf29, 16);
export const STILE8 = () => createSimpleInstr(0xcf2a, 16);
export const STULE8 = () => createSimpleInstr(0xcf2b, 16);
export const LDIX = () => createSimpleInstr(0xd700, 16);
export const LDUX = () => createSimpleInstr(0xd701, 16);
export const PLDIX = () => createSimpleInstr(0xd702, 16);
export const PLDUX = () => createSimpleInstr(0xd703, 16);
export const LDIXQ = () => createSimpleInstr(0xd704, 16);
export const LDUXQ = () => createSimpleInstr(0xd705, 16);
export const PLDIXQ = () => createSimpleInstr(0xd706, 16);
export const PLDUXQ = () => createSimpleInstr(0xd707, 16);
export const LDSLICEX = () => createSimpleInstr(0xd718, 16);
export const PLDSLICEX = () => createSimpleInstr(0xd719, 16);
export const LDSLICEXQ = () => createSimpleInstr(0xd71a, 16);
export const PLDSLICEXQ = () => createSimpleInstr(0xd71b, 16);
export const LDILE4 = () => createSimpleInstr(0xd750, 16);
export const LDULE4 = () => createSimpleInstr(0xd751, 16);
export const LDILE8 = () => createSimpleInstr(0xd752, 16);
export const LDULE8 = () => createSimpleInstr(0xd753, 16);
export const PLDILE4 = () => createSimpleInstr(0xd754, 16);
export const PLDULE4 = () => createSimpleInstr(0xd755, 16);
export const PLDILE8 = () => createSimpleInstr(0xd756, 16);
export const PLDULE8 = () => createSimpleInstr(0xd757, 16);
export const LDILE4Q = () => createSimpleInstr(0xd758, 16);
export const LDULE4Q = () => createSimpleInstr(0xd759, 16);
export const LDILE8Q = () => createSimpleInstr(0xd75a, 16);
export const LDULE8Q = () => createSimpleInstr(0xd75b, 16);
export const PLDILE4Q = () => createSimpleInstr(0xd75c, 16);
export const PLDULE4Q = () => createSimpleInstr(0xd75d, 16);
export const PLDILE8Q = () => createSimpleInstr(0xd75e, 16);
export const PLDULE8Q = () => createSimpleInstr(0xd75f, 16);
export const DICTIGETJMP = () => createSimpleInstr(0xf4a0, 16);
export const DICTUGETJMP = () => createSimpleInstr(0xf4a1, 16);
export const DICTIGETEXEC = () => createSimpleInstr(0xf4a2, 16);
export const DICTUGETEXEC = () => createSimpleInstr(0xf4a3, 16);
export const DICTIGETJMPZ = () => createSimpleInstr(0xf4bc, 16);
export const DICTUGETJMPZ = () => createSimpleInstr(0xf4bd, 16);
export const DICTIGETEXECZ = () => createSimpleInstr(0xf4be, 16);
export const DICTUGETEXECZ = () => createSimpleInstr(0xf4bf, 16);
export const DICTGET = () => createSimpleInstr(0xf40a, 16);
export const DICTGETREF = () => createSimpleInstr(0xf40b, 16);
export const DICTIGET = () => createSimpleInstr(0xf40c, 16);
export const DICTIGETREF = () => createSimpleInstr(0xf40d, 16);
export const DICTUGET = () => createSimpleInstr(0xf40e, 16);
export const DICTUGETREF = () => createSimpleInstr(0xf40f, 16);
export const DICTSET = () => createSimpleInstr(0xf412, 16);
export const DICTSETREF = () => createSimpleInstr(0xf413, 16);
export const DICTISET = () => createSimpleInstr(0xf414, 16);
export const DICTISETREF = () => createSimpleInstr(0xf415, 16);
export const DICTUSET = () => createSimpleInstr(0xf416, 16);
export const DICTUSETREF = () => createSimpleInstr(0xf417, 16);
export const DICTSETGET = () => createSimpleInstr(0xf41a, 16);
export const DICTSETGETREF = () => createSimpleInstr(0xf41b, 16);
export const DICTISETGET = () => createSimpleInstr(0xf41c, 16);
export const DICTISETGETREF = () => createSimpleInstr(0xf41d, 16);
export const DICTUSETGET = () => createSimpleInstr(0xf41e, 16);
export const DICTUSETGETREF = () => createSimpleInstr(0xf41f, 16);
export const DICTREPLACE = () => createSimpleInstr(0xf422, 16);
export const DICTREPLACEREF = () => createSimpleInstr(0xf423, 16);
export const DICTIREPLACE = () => createSimpleInstr(0xf424, 16);
export const DICTIREPLACEREF = () => createSimpleInstr(0xf425, 16);
export const DICTUREPLACE = () => createSimpleInstr(0xf426, 16);
export const DICTUREPLACEREF = () => createSimpleInstr(0xf427, 16);
export const DICTREPLACEGET = () => createSimpleInstr(0xf42a, 16);
export const DICTREPLACEGETREF = () => createSimpleInstr(0xf42b, 16);
export const DICTIREPLACEGET = () => createSimpleInstr(0xf42c, 16);
export const DICTIREPLACEGETREF = () => createSimpleInstr(0xf42d, 16);
export const DICTUREPLACEGET = () => createSimpleInstr(0xf42e, 16);
export const DICTUREPLACEGETREF = () => createSimpleInstr(0xf42f, 16);
export const DICTADD = () => createSimpleInstr(0xf432, 16);
export const DICTADDREF = () => createSimpleInstr(0xf433, 16);
export const DICTIADD = () => createSimpleInstr(0xf434, 16);
export const DICTIADDREF = () => createSimpleInstr(0xf435, 16);
export const DICTUADD = () => createSimpleInstr(0xf436, 16);
export const DICTUADDREF = () => createSimpleInstr(0xf437, 16);
export const DICTADDGET = () => createSimpleInstr(0xf43a, 16);
export const DICTADDGETREF = () => createSimpleInstr(0xf43b, 16);
export const DICTIADDGET = () => createSimpleInstr(0xf43c, 16);
export const DICTIADDGETREF = () => createSimpleInstr(0xf43d, 16);
export const DICTUADDGET = () => createSimpleInstr(0xf43e, 16);
export const DICTUADDGETREF = () => createSimpleInstr(0xf43f, 16);
export const DICTDELGET = () => createSimpleInstr(0xf462, 16);
export const DICTDELGETREF = () => createSimpleInstr(0xf463, 16);
export const DICTIDELGET = () => createSimpleInstr(0xf464, 16);
export const DICTIDELGETREF = () => createSimpleInstr(0xf465, 16);
export const DICTUDELGET = () => createSimpleInstr(0xf466, 16);
export const DICTUDELGETREF = () => createSimpleInstr(0xf467, 16);
export const DICTMIN = () => createSimpleInstr(0xf482, 16);
export const DICTMINREF = () => createSimpleInstr(0xf483, 16);
export const DICTIMIN = () => createSimpleInstr(0xf484, 16);
export const DICTIMINREF = () => createSimpleInstr(0xf485, 16);
export const DICTUMIN = () => createSimpleInstr(0xf486, 16);
export const DICTUMINREF = () => createSimpleInstr(0xf487, 16);
export const DICTMAX = () => createSimpleInstr(0xf48a, 16);
export const DICTMAXREF = () => createSimpleInstr(0xf48b, 16);
export const DICTIMAX = () => createSimpleInstr(0xf48c, 16);
export const DICTIMAXREF = () => createSimpleInstr(0xf48d, 16);
export const DICTUMAX = () => createSimpleInstr(0xf48e, 16);
export const DICTUMAXREF = () => createSimpleInstr(0xf48f, 16);
export const DICTREMMIN = () => createSimpleInstr(0xf492, 16);
export const DICTREMMINREF = () => createSimpleInstr(0xf493, 16);
export const DICTIREMMIN = () => createSimpleInstr(0xf494, 16);
export const DICTIREMMINREF = () => createSimpleInstr(0xf495, 16);
export const DICTUREMMIN = () => createSimpleInstr(0xf496, 16);
export const DICTUREMMINREF = () => createSimpleInstr(0xf497, 16);
export const DICTREMMAX = () => createSimpleInstr(0xf49a, 16);
export const DICTREMMAXREF = () => createSimpleInstr(0xf49b, 16);
export const DICTIREMMAX = () => createSimpleInstr(0xf49c, 16);
export const DICTIREMMAXREF = () => createSimpleInstr(0xf49d, 16);
export const DICTUREMMAX = () => createSimpleInstr(0xf49e, 16);
export const DICTUREMMAXREF = () => createSimpleInstr(0xf49f, 16);
export const DICTSETB = () => createSimpleInstr(0xf441, 16);
export const DICTISETB = () => createSimpleInstr(0xf442, 16);
export const DICTUSETB = () => createSimpleInstr(0xf443, 16);
export const DICTSETGETB = () => createSimpleInstr(0xf445, 16);
export const DICTISETGETB = () => createSimpleInstr(0xf446, 16);
export const DICTUSETGETB = () => createSimpleInstr(0xf447, 16);
export const DICTREPLACEB = () => createSimpleInstr(0xf449, 16);
export const DICTIREPLACEB = () => createSimpleInstr(0xf44a, 16);
export const DICTUREPLACEB = () => createSimpleInstr(0xf44b, 16);
export const DICTREPLACEGETB = () => createSimpleInstr(0xf44d, 16);
export const DICTIREPLACEGETB = () => createSimpleInstr(0xf44e, 16);
export const DICTUREPLACEGETB = () => createSimpleInstr(0xf44f, 16);
export const DICTADDB = () => createSimpleInstr(0xf451, 16);
export const DICTIADDB = () => createSimpleInstr(0xf452, 16);
export const DICTUADDB = () => createSimpleInstr(0xf453, 16);
export const DICTADDGETB = () => createSimpleInstr(0xf455, 16);
export const DICTIADDGETB = () => createSimpleInstr(0xf456, 16);
export const DICTUADDGETB = () => createSimpleInstr(0xf457, 16);
export const DICTDEL = () => createSimpleInstr(0xf459, 16);
export const DICTIDEL = () => createSimpleInstr(0xf45a, 16);
export const DICTUDEL = () => createSimpleInstr(0xf45b, 16);
export const DICTGETOPTREF = () => createSimpleInstr(0xf469, 16);
export const DICTIGETOPTREF = () => createSimpleInstr(0xf46a, 16);
export const DICTUGETOPTREF = () => createSimpleInstr(0xf46b, 16);
export const DICTSETGETOPTREF = () => createSimpleInstr(0xf46d, 16);
export const DICTISETGETOPTREF = () => createSimpleInstr(0xf46e, 16);
export const DICTUSETGETOPTREF = () => createSimpleInstr(0xf46f, 16);
export const SUBDICTGET = () => createSimpleInstr(0xf4b1, 16);
export const SUBDICTIGET = () => createSimpleInstr(0xf4b2, 16);
export const SUBDICTUGET = () => createSimpleInstr(0xf4b3, 16);
export const SUBDICTRPGET = () => createSimpleInstr(0xf4b5, 16);
export const SUBDICTIRPGET = () => createSimpleInstr(0xf4b6, 16);
export const SUBDICTURPGET = () => createSimpleInstr(0xf4b7, 16);
export const THROWANY = () => createSimpleInstr(0xf2f0, 16);
export const THROWARGANY = () => createSimpleInstr(0xf2f1, 16);
export const THROWANYIFNOT = () => createSimpleInstr(0xf2f4, 16);
export const THROWARGANYIFNOT = () => createSimpleInstr(0xf2f5, 16);
export const DICTGETNEXT = () => createSimpleInstr(0xf474, 16);
export const DICTGETNEXTEQ = () => createSimpleInstr(0xf475, 16);
export const DICTGETPREV = () => createSimpleInstr(0xf476, 16);
export const DICTGETPREVEQ = () => createSimpleInstr(0xf477, 16);
export const DICTIGETNEXT = () => createSimpleInstr(0xf478, 16);
export const DICTIGETNEXTEQ = () => createSimpleInstr(0xf479, 16);
export const DICTIGETPREV = () => createSimpleInstr(0xf47a, 16);
export const DICTIGETPREVEQ = () => createSimpleInstr(0xf47b, 16);
export const DICTUGETNEXT = () => createSimpleInstr(0xf47c, 16);
export const DICTUGETNEXTEQ = () => createSimpleInstr(0xf47d, 16);
export const DICTUGETPREV = () => createSimpleInstr(0xf47e, 16);
export const DICTUGETPREVEQ = () => createSimpleInstr(0xf47f, 16);
export const ADDINT = createUnaryInstr(0xa6, 8, int(8));
export const MULINT = createUnaryInstr(0xa7, 8, int(8));
export const QADDINT = createUnaryInstr(0xb7a6, 16, int(8));
export const QMULINT = createUnaryInstr(0xb7a7, 16, int(8));
export const EQINT = createUnaryInstr(0xc0, 8, int(8));
export const LESSINT = createUnaryInstr(0xc1, 8, int(8));
export const GTINT = createUnaryInstr(0xc2, 8, int(8));
export const NEQINT = createUnaryInstr(0xc3, 8, int(8));
export const QEQINT = createUnaryInstr(0xb7c0, 16, int(8));
export const QLESSINT = createUnaryInstr(0xb7c1, 16, int(8));
export const QGTINT = createUnaryInstr(0xb7c2, 16, int(8));
export const QNEQINT = createUnaryInstr(0xb7c3, 16, int(8));
export const PUSHPOW2DEC = createUnaryInstr(0x84, 8, delta(1, uint(8)));
export const PUSHNEGPOW2 = createUnaryInstr(0x85, 8, delta(1, uint(8)));
export const FITS = createUnaryInstr(0xb4, 8, delta(1, uint(8)));
export const UFITS = createUnaryInstr(0xb5, 8, delta(1, uint(8)));
export const QFITS = createUnaryInstr(0xb7b4, 16, delta(1, uint(8)));
export const QUFITS = createUnaryInstr(0xb7b5, 16, delta(1, uint(8)));
export const SETCONTCTRMANY = createUnaryInstr(0xede3, 16, delta(1, uint(8)));
export const CALLCCARGS = createBinaryInstr(0xdb36, 16, uint(4), uint(4));
export const TRYARGS = createBinaryInstr(0xf3, 8, uint(4), uint(4));
export const PLDREFIDX = createUnaryInstr(0x35d3, 14, uint(2));
export const CHASHI = createUnaryInstr(0x35da, 14, uint(2));
export const CDEPTHI = createUnaryInstr(0x35db, 14, uint(2));
export const JMPDICT = createUnaryInstr(0x3c5, 10, uint(14));
export const PREPAREDICT = createUnaryInstr(0x3c6, 10, uint(14));
export const THROWARG = createUnaryInstr(0x1e59, 13, uint(11));
export const THROWARGIF = createUnaryInstr(0x1e5b, 13, uint(11));
export const THROWARGIFNOT = createUnaryInstr(0x1e5d, 13, uint(11));
export const JMPXARGS = createUnaryInstr(0xdb1, 12, uint(4));
export const RETARGS = createUnaryInstr(0xdb2, 12, uint(4));
export const RETURNARGS = createUnaryInstr(0xed0, 12, uint(4));
export const BLKDROP = createUnaryInstr(0x5f0, 12, uint(4));
export const TUPLE = createUnaryInstr(0x6f0, 12, uint(4));
export const INDEX = createUnaryInstr(0x6f1, 12, uint(4));
export const UNTUPLE = createUnaryInstr(0x6f2, 12, uint(4));
export const UNPACKFIRST = createUnaryInstr(0x6f3, 12, uint(4));
export const EXPLODE = createUnaryInstr(0x6f4, 12, uint(4));
export const SETINDEX = createUnaryInstr(0x6f5, 12, uint(4));
export const INDEXQ = createUnaryInstr(0x6f6, 12, uint(4));
export const SETINDEXQ = createUnaryInstr(0x6f7, 12, uint(4));
export const XC2PU = createTernaryInstr(0x541, 12, uint(4), uint(4), uint(4));
export const XCPU2 = createTernaryInstr(0x543, 12, uint(4), uint(4), uint(4));
export const PUSH3 = createTernaryInstr(0x547, 12, uint(4), uint(4), uint(4));
export const XCHG2 = createBinaryInstr(0x50, 8, uint(4), uint(4));
export const XCPU = createBinaryInstr(0x51, 8, uint(4), uint(4));
export const PUSH2 = createBinaryInstr(0x53, 8, uint(4), uint(4));
export const PUXC = createBinaryInstr(0x52, 8, uint(4), delta(-1, uint(4)));
export const XCPUXC = createTernaryInstr(0x542, 12, uint(4), uint(4), delta(-1, uint(4)));
export const PUXC2 = createTernaryInstr(0x544, 12, uint(4), delta(-1, uint(4)), delta(-1, uint(4)));
export const PUXCPU = createTernaryInstr(0x545, 12, uint(4), delta(-1, uint(4)), delta(-1, uint(4)));
export const PU2XC = createTernaryInstr(0x546, 12, uint(4), delta(-1, uint(4)), delta(-2, uint(4)));
export const BLKSWAP = createBinaryInstr(0x55, 8, delta(1, uint(4)), delta(1, uint(4)));
export const REVERSE = createBinaryInstr(0x5e, 8, delta(2, uint(4)), uint(4));
export const SETCONTARGS = createBinaryInstr(0xec, 8, uint(4), delta(-1, uint(4)));
export const BLESSARGS = createBinaryInstr(0xee, 8, uint(4), delta(-1, uint(4)));
export const STIR = createUnaryInstr(0xcf0a, 16, delta(1, uint(8)));
export const STUR = createUnaryInstr(0xcf0b, 16, delta(1, uint(8)));
export const STIQ = createUnaryInstr(0xcf0c, 16, delta(1, uint(8)));
export const STUQ = createUnaryInstr(0xcf0d, 16, delta(1, uint(8)));
export const STIRQ = createUnaryInstr(0xcf0e, 16, delta(1, uint(8)));
export const STURQ = createUnaryInstr(0xcf0f, 16, delta(1, uint(8)));
export const PLDI = createUnaryInstr(0xd70a, 16, delta(1, uint(8)));
export const PLDU = createUnaryInstr(0xd70b, 16, delta(1, uint(8)));
export const LDIQ = createUnaryInstr(0xd70c, 16, delta(1, uint(8)));
export const LDUQ = createUnaryInstr(0xd70d, 16, delta(1, uint(8)));
export const PLDIQ = createUnaryInstr(0xd70e, 16, delta(1, uint(8)));
export const PLDUQ = createUnaryInstr(0xd70f, 16, delta(1, uint(8)));
export const PLDUZ = createUnaryInstr(0x1ae2, 13, plduzArg);
export const PLDSLICE = createUnaryInstr(0xd71d, 16, delta(1, uint(8)));
export const LDSLICEQ = createUnaryInstr(0xd71e, 16, delta(1, uint(8)));
export const PLDSLICEQ = createUnaryInstr(0xd71f, 16, delta(1, uint(8)));
export const IFBITJMP = createUnaryInstr(0x71c, 11, uint(5));
export const IFNBITJMP = createUnaryInstr(0x71d, 11, uint(5));
export const INDEX2 = createBinaryInstr(0x6fb, 12, uint(2), uint(2));
export const INDEX3 = createTernaryInstr(0x1bf, 10, uint(2), uint(2), uint(2));
export const PUSHPOW2 = createFixedRangeInstr(0x8300, 8, 8, delta(1, uint(8)));
export const BLKPUSH = createFixedRangeInstr(0x5f10, 8, 8, seq2(uint(4), uint(4)));
export const BLKDROP2 = createFixedRangeInstr(0x6c10, 8, 8, seq2(uint(4), uint(4)));
export const GETGLOB = createFixedRangeInstr(0xf841, 11, 5, uint(5));
export const SETGLOB = createFixedRangeInstr(0xf861, 11, 5, uint(5));
export const GETPARAM = createFixedRangeInstr(0xf820, 12, 4, uint(4));
export const THROWANYIF = () => createSimpleInstr(0xf2f2, 16);
export const THROWARGANYIF = () => createSimpleInstr(0xf2f3, 16);
export const SETCONTCTR = createFixedRangeInstr(0xed60, 12, 4, control);
export const SETRETCTR = createFixedRangeInstr(0xed70, 12, 4, control);
export const SETALTCTR = createFixedRangeInstr(0xed80, 12, 4, control);
export const POPSAVE = createFixedRangeInstr(0xed90, 12, 4, control);
export const SAVECTR = createFixedRangeInstr(0xeda0, 12, 4, control);
export const SAVEALTCTR = createFixedRangeInstr(0xedb0, 12, 4, control);
export const SAVEBOTHCTR = createFixedRangeInstr(0xedc0, 12, 4, control);
export const RUNVM = createUnaryInstr(0xdb4, 12, uint(12));
export const SWAP2 = () => createSimpleInstr(0x5a, 8);
export const DROP2 = () => createSimpleInstr(0x5b, 8);
export const DUP2 = () => createSimpleInstr(0x5c, 8);
export const OVER2 = () => createSimpleInstr(0x5d, 8);
export const ADDRSHIFT_MOD = createUnaryInstr(0xa930, 16, delta(1, uint(8)));
export const ADDRSHIFTR_MOD = createUnaryInstr(0xa931, 16, delta(1, uint(8)));
export const ADDRSHIFTC_MOD = createUnaryInstr(0xa932, 16, delta(1, uint(8)));
export const RSHIFT_ = createUnaryInstr(0xa934, 16, delta(1, uint(8)));
export const RSHIFTR_ = createUnaryInstr(0xa935, 16, delta(1, uint(8)));
export const RSHIFTC_ = createUnaryInstr(0xa936, 16, delta(1, uint(8)));
export const MODPOW2_ = createUnaryInstr(0xa938, 16, delta(1, uint(8)));
export const MODPOW2R_ = createUnaryInstr(0xa939, 16, delta(1, uint(8)));
export const MODPOW2C_ = createUnaryInstr(0xa93a, 16, delta(1, uint(8)));
export const RSHIFT_MOD = createUnaryInstr(0xa93c, 16, delta(1, uint(8)));
export const RSHIFTR_MOD = createUnaryInstr(0xa93d, 16, delta(1, uint(8)));
export const RSHIFTC_MOD = createUnaryInstr(0xa93e, 16, delta(1, uint(8)));
export const MULADDRSHIFT_MOD = createUnaryInstr(0xa9b0, 16, delta(1, uint(8)));
export const MULADDRSHIFTR_MOD = createUnaryInstr(0xa9b1, 16, delta(1, uint(8)));
export const MULADDRSHIFTC_MOD = createUnaryInstr(0xa9b2, 16, delta(1, uint(8)));
export const MULRSHIFT_ = createUnaryInstr(0xa9b4, 16, delta(1, uint(8)));
export const MULRSHIFTR_ = createUnaryInstr(0xa9b5, 16, delta(1, uint(8)));
export const MULRSHIFTC_ = createUnaryInstr(0xa9b6, 16, delta(1, uint(8)));
export const MULMODPOW2_ = createUnaryInstr(0xa9b8, 16, delta(1, uint(8)));
export const MULMODPOW2R_ = createUnaryInstr(0xa9b9, 16, delta(1, uint(8)));
export const MULMODPOW2C_ = createUnaryInstr(0xa9ba, 16, delta(1, uint(8)));
export const MULRSHIFT_MOD = createUnaryInstr(0xa9bc, 16, delta(1, uint(8)));
export const MULRSHIFTR_MOD = createUnaryInstr(0xa9bd, 16, delta(1, uint(8)));
export const MULRSHIFTC_MOD = createUnaryInstr(0xa9be, 16, delta(1, uint(8)));
export const LSHIFT_ADDDIVMOD = createUnaryInstr(0xa9d0, 16, delta(1, uint(8)));
export const LSHIFT_ADDDIVMODR = createUnaryInstr(0xa9d1, 16, delta(1, uint(8)));
export const LSHIFT_ADDDIVMODC = createUnaryInstr(0xa9d2, 16, delta(1, uint(8)));
export const LSHIFT_DIV = createUnaryInstr(0xa9d4, 16, delta(1, uint(8)));
export const LSHIFT_DIVR = createUnaryInstr(0xa9d5, 16, delta(1, uint(8)));
export const LSHIFT_DIVC = createUnaryInstr(0xa9d6, 16, delta(1, uint(8)));
export const LSHIFT_MOD = createUnaryInstr(0xa9d8, 16, delta(1, uint(8)));
export const LSHIFT_MODR = createUnaryInstr(0xa9d9, 16, delta(1, uint(8)));
export const LSHIFT_MODC = createUnaryInstr(0xa9da, 16, delta(1, uint(8)));
export const LSHIFT_DIVMOD = createUnaryInstr(0xa9dc, 16, delta(1, uint(8)));
export const LSHIFT_DIVMODR = createUnaryInstr(0xa9dd, 16, delta(1, uint(8)));
export const LSHIFT_DIVMODC = createUnaryInstr(0xa9de, 16, delta(1, uint(8)));
export const HASHEXT = createUnaryInstr(0xf904, 16, hash);
export const HASHEXTR = createUnaryInstr(0xf905, 16, hash);
export const HASHEXTA = createUnaryInstr(0xf906, 16, hash);
export const HASHEXTAR = createUnaryInstr(0xf907, 16, hash);
export const STREF = () => createSimpleInstr(0xcc, 8);
export const STSLICE = () => createSimpleInstr(0xce, 8);
export const XCHG3 = createTernaryInstr(0x4, 4, uint(4), uint(4), uint(4));
export const STI = createUnaryInstr(0xca, 8, delta(1, uint(8)));
export const STU = createUnaryInstr(0xcb, 8, delta(1, uint(8)));
export const LDI = createUnaryInstr(0xd2, 8, delta(1, uint(8)));
export const LDU = createUnaryInstr(0xd3, 8, delta(1, uint(8)));
export const LDSLICE = createUnaryInstr(0xd6, 8, delta(1, uint(8)));
export const LSHIFT = () => createSimpleInstr(0xac, 8);
export const LSHIFT_1 = createUnaryInstr(0xaa, 8, delta(1, uint(8)));
export const QLSHIFT = () => createSimpleInstr(0xb7ac, 16);
export const QLSHIFT_1 = createUnaryInstr(0xb7aa, 16, delta(1, uint(8)));
export const BCHKBITS = () => createSimpleInstr(0xcf39, 16);
export const BCHKBITS_1 = createUnaryInstr(0xcf38, 16, delta(1, uint(8)));
export const BCHKBITSQ = () => createSimpleInstr(0xcf3d, 16);
export const BCHKBITSQ_1 = createUnaryInstr(0xcf3c, 16, delta(1, uint(8)));
export const RSHIFT = () => createSimpleInstr(0xad, 8);
export const RSHIFT_1 = createUnaryInstr(0xab, 8, delta(1, uint(8)));
export const QRSHIFT = () => createSimpleInstr(0xb7ad, 16);
export const QRSHIFT_1 = createUnaryInstr(0xb7ab, 16, delta(1, uint(8)));
export const CALLDICT = createUnaryInstr(0xf0, 8, uint(8));
export const CALLDICT_1 = createUnaryInstr(0x3c4, 10, uint(14));
export const THROW_1 = createUnaryInstr(0x1e58, 13, uint(11));
export const THROWIF = createUnaryInstr(0x3c9, 10, uint(6));
export const THROWIF_1 = createUnaryInstr(0x1e5a, 13, uint(11));
export const THROWIFNOT = createUnaryInstr(0x3ca, 10, uint(6));
export const THROWIFNOT_1 = createUnaryInstr(0x1e5c, 13, uint(11));
export const PUSHINT = createUnaryInstr(0x7, 4, tinyInt);
export const PUSHINT_1 = createUnaryInstr(0x81, 8, int(16));
export const PUSHINT_2 = createUnaryInstr(0x80, 8, int(8));
export const XCHG = createUnaryInstr(0x11, 8, uint(8));
export const XCHG_1 = createUnaryInstr(0x10, 8, xchgArgs);
export const XCHG_3 = createFixedRangeInstr(0x12, 4, 4, seq2(s1, stack(4)));
export const DUMPSTK = () => createSimpleInstr(0xfe00, 16);
export const DEBUG = createFixedRangeInstr(0xfe01, 8, 8, uint(8));
export const STRDUMP = () => createSimpleInstr(0xfe14, 16);
export const DEBUG_1 = createFixedRangeInstr(0xfe15, 8, 8, uint(8));
export const DUMP = createUnaryInstr(0xfe2, 12, uint(4));
export const DEBUG_2 = createFixedRangeInstr(0xfe30, 8, 8, uint(8));
export const PUSHCTR = createFixedRangeInstr(0xed40, 12, 4, control);
export const PUSH_LONG = createUnaryInstr(0x56, 8, uint(8));
export const PUSH = createFixedRangeInstr(0x22, 4, 4, uint(4));
export const POPCTR = createFixedRangeInstr(0xed50, 12, 4, control);
export const POP_LONG = createUnaryInstr(0x57, 8, uint(8));
export const POP = createFixedRangeInstr(0x32, 4, 4, uint(4));
export const CALLXARGS = createBinaryInstr(0xdb0, 12, uint(4), minusOne);
export const CALLXARGS_1 = createBinaryInstr(0xda, 8, uint(4), uint(4));
export const SETCP = createFixedRangeInstr(0xff00, 8, 8, uint(8));
export const SETCP_1 = createFixedRangeInstr(0xfff1, 8, 8, delta(-256, uint(8)));
